print ("")
print ("")
print ("")
print ("Why was the frog late to work?")
input ()
print ("Because his car got toad!!")
input ()
name = input("What's your name?")
print(f"Hello {name}!")
print ("Would you like to hear another joke?")
input ()
print ("Did you here about the kidnapping at school?")
input ()
print ("Its ok, he woke up")
color = input ("What's your favorite color?")
print (f"I like {color} too, {name}!")
class = input ("What's your favorite class?")
print (f"Oooh I like {class} too! It's so much fun")
answer1 = input ("Do you want to here another joke?")
if answer1 == "yes"