name = input ("What's your name? ")
print (f"Hi {name}! Let's play a mad lib! Click enter to continue")
input ()
adjective1 = input ("Give me an adjective:")
nationality1 = input ("Give me a nationality, for example french or italian:")
person1 = input ("Now, give me the name of a person:")
noun1 = input ("Give me a noun:")
adjective2 = input ("Give me another adjective:")
noun2 = input ("Give me another noun:")
adjective3 = input ("Another adjective:")
adjective4 = input ("Another adjective (hang in there): ")
nouns1 = input ("Plural noun:")
noun3 = input ("Another noun (last noun!): ")
number1 = input ("Any number: ")
shapes1 = input ("Shapes: ")
food1 = input ("A food: ")
food2 = input ("Another food: ")
number2 = input ("Another number (last one!!!) ")
input()
print (f"Ok, ready to see the story you made, {name}?")
input ()
print ("Pizza, Pizza")
input ()
print (f"Pizza was invented by a {adjective1} {nationality1} chef named {person1}.")
print ("Click enter to continue")
input ()
print (f"To make pizza, you need to take a lump of {noun1}, and make a thin, round, {adjective2} {noun2}.")
input ()
print (f"Then you cover it with {adjective3} sauce, {adjective4} cheese, and fresh chopped {nouns}. ")
print (f"Next you have to bake it in a very hot {noun3}. ")
